
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

# load custom PATH additions
source $HOME/.zshpathvar

# history completion
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward

# setup fnm, which is a node version manager written in rust
eval "$(fnm env)"

# initialize zoxide, replacement for z written in rust
eval "$(zoxide init zsh --cmd z --hook pwd)"

# initialize starship, a command prompt customizer written in rust 
eval $(starship init zsh)

# load command aliases
source $HOME/.zshaliases

# Google cloud sdk initialization
# initialize zsh completions
autoload -U compinit; compinit
_comp_options+=(globdots) # With hidden files
# source /my/path/to/zsh/completion.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '$HOME/google-cloud-sdk/path.zsh.inc' ]; then . '$HOME/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '$HOME/google-cloud-sdk/completion.zsh.inc' ]; then . '$HOME/google-cloud-sdk/completion.zsh.inc'; fi

# backup env
cp $HOME/.zshenv $ZDOTDIR/.zshenv.backup
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####

