name: Tag latest configurations

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.TAGGING_TOKEN }}
  WITH_V: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump repo version
      id: bumpTag
      uses: anothrNick/github-tag-action@1.36.0